export const rooms_info_hellper = [
    {
        id: 1,
        name: 'Three Single and One Double beds',
        imageSrc: '/images/app1.jpg',
        people: 5,
        beds: 3,
        price: 44,
        alt: 'Balabusic room image',
        type: "1. Apartment",
    },
    {
        id: 2,
        name: 'One Single and One Double beds',
        imageSrc: '/images/app2.jpg',
        people: 3,
        beds: 2,
        price: 33,
        alt: 'Balabusic room image',
        type: "2. Apartment",
    },
    {
        id: 3,
        name: 'Two Single beds',
        imageSrc: '/images/room.JPG',
        people: 2,
        beds: 2,
        price: 22,
        alt: 'Balabusic room image',
        type: "3. Studio",
    },
    {
        id: 4,
        name: 'One Double bet',
        imageSrc: '/images/app7.jpg',
        people: 2,
        beds: 1,
        price: 22,
        alt: 'Balabusic room image',
        type: "4. Studio",
    },
    {
        id: 5,
        name: 'Three Single and One Double beds',
        imageSrc: '/images/app5.jpg',
        people: 5,
        beds: 3,
        price: 33,
        alt: 'Balabusic room image',
        type: "5. Apartment",
    },
    {
        id: 6,
        name: 'Two Single and One Double beds',
        imageSrc: '/images/app6.jpg',
        people: 4,
        beds: 3,
        price: 22,
        alt: 'Balabusic room image',
        type: "6. Apartment",
    },
    {
        id: 7,
        name: 'One Single and One Double beds',
        imageSrc: '/images/app4.jpg',
        people: 3,
        beds: 2,
        price: 23,
        alt: 'Balabusic room image',
        type: "7. Studio",
    },
    {
        id: 8,
        name: 'One Single and Two double beds',
        imageSrc: '/images/app8.jpg',
        people: 5,
        beds: 3,
        price: 22,
        alt: 'Balabusic room image',
        type: "8. Apartment",
    },
    {
        id: 9,
        name: 'One Single and Two double beds',
        imageSrc: '/images/condo.jpg',
        people: 5,
        beds: 3,
        price: 33,
        alt: 'Balabusic room image',
        type: "9. Apartment",
    },
]